### ISSUE TITLE
Errors when writing import/export functions for gzip-compressed csv files i.e. ".csv.gz" files

### ISSUE THREAD

**Issue by trevorld** [leeper/rio#123]
I tried to write my own `import` and `export` functions to directly read gzip compressed csv files using the relevant functions from base R:

```
 import.rio_csv.gz <- function(filename) { read.csv(filename, stringsAsFactors=FALSE) }
 export.rio_csv.gz <- function(df, filename) { write.csv(df, gzfile(filename), row.names=FALSE) }
```

Everything works fine if I use them directly

```
> export.rio_csv.gz(iris, "iris.csv.gz")
> iris2 <- import.rio_csv.gz("iris.csv.gz")
> all.equal(iris2, dplyr::mutate(iris, Species=as.character(Species)))
[1] TRUE
```

But I get an error if I try to use `import` directly.  I guess `rio::import` thinks that any file ending in ".gz" is automatically a compressed tarball that needs to be unpacked first instead of a compressed file that could be read directly into R from disc.  

```
> import("iris.csv.gz")
/bin/tar: This does not look like a tar archive
/bin/tar: Skipping to next header
/bin/tar: Exiting with failure status due to previous errors
Warning: running command '/bin/tar -ztf 'iris.csv.gz'' had status 2
/bin/tar: This does not look like a tar archive
/bin/tar: Skipping to next header
/bin/tar: NA: Not found in archive
/bin/tar: Exiting with failure status due to previous errors
 Warning in untar(file, files = file_list[which], exdir = d) :
 ‘/bin/tar -zxf 'iris.csv.gz' -C '/tmp/Rtmp88cRuT/file587b1be66730' 'NA'’ returned error code 2
 Error in get_ext(file) : 'file' has no extension
```

I also get an error if I try to read in a file that I exported using `export` directly.  It looks like calling `export` also adds some kind of embedded null that you don't get if you simply call `export.rio_csv.gz`.  Maybe it is trying to create a tarball?

```
> export(iris, "iris_alt.csv.gz")
> iris2 <- import.rio_csv.gz("iris_alt.csv.gz")
Warning in read.table(file = file, header = header, sep = sep, quote = quote,  :
 line 1 appears to contain embedded nulls
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names
 > readLines(gzfile("iris_alt.csv.gz"))[1]
 Warning: line 1 appears to contain an embedded nul
 Warning: line 152 appears to contain an embedded nul
 [1] "./iris_alt.csv"
 > export.rio_csv.gz(iris, "iris.csv.gz")
 > readLines(gzfile("iris.csv.gz"))[1]
 [1] "\"Sepal.Length\",\"Sepal.Width\",\"Petal.Length\",\"Petal.Width\",\"Species\""
```

**Comment by jsonbecker** [comment]
Hi @trevorld,

I can confirm this issue. Here's the source. In a non-exported function, `rio` attempts to unzip any compressed file passed to it. Internally, it uses the command `utils::untar()`, which does support `gzip` files, but assumes the output is a tar file, as in the popular `.tar.gz` convention.

I am going to think about a PR to submit to address this. I am not sure if we're going to change the automatic behavior on tar/gz files, because it's pretty deeply embedded in some other functionality. I would normally recommend that in the mean time you can call `import` and `export` with an explicit `format` parameter set to `csv.gz`. However, because the compression logic comes before the format is read, this will not work. I am going to consider submitting a PR that changes this behavior as well so that an explicit format skips some of that logic. @leeper what do you think? Is that worth consideration as a separate issue and a PR?

**Comment by jsonbecker** [comment]
I should also note another couple of errors. These functions should start with `.`, since it's `.import` and `.export` that actually are the s3methods. `import` and `export` do some preparation before calling them.

Additionally, `export` is going to pass `x` and `file` from `export` down, so a more consistent `.export` method would look like this:


```
.export.rio_customimport <- function(file, x){
  write.csv(x = x , file = file, row.names = FALSE)
}
```

Now, in your case, the `.gz` ending gets you again, as `export` does some fancy work to assume that you want us to do the compression for you. In fact, `export(iris. file = 'iris.gz', format ='csv')` actually works out of the box.

**Comment by trevorld** [comment]
Although it works out of the box ``export(iris. file = 'iris.gz', format ='csv')``does not create a gzip compressed csv file that can be directly read by ``read.csv`` in R nor the csv module in python (using `gzip.open`) nor can it be easily queried on the commandline combining ``zcat`` with the tools from ``csvkit`` ( https://csvkit.readthedocs.io/en/latest/scripts/csvsql.html ) such as ``csvcut``, ``csvgrep``, etc.  It instead seems to create a compressed tarball that contains a single csv file.  I'm really confused by your usage of ".gz" file ending.  By long-time gzip convention ".gz" means the file has been compressed with "gzip" and by default gzip will add a ".gz" added to the end of the original filename to signify it has been compressed with gzip BUT DOES NOT wrap it into a tar container.  Gzip is not a container format, it is a compression algorithm usually used on single files.  If you uncompress the file with "gzip -d", "gunzip", or "zcat" you get the file again, not a tar file which contains the file.   gzip is often used to compress tar file container but those files usually end in .tar.gz or .tgz and NOT simply a .gz i.e. see  https://en.wikipedia.org/wiki/Tar_(computing) .

     bash$ gzip iris.csv   # this produces compressed csv file iris.csv.gz without any kind of tar container
    bash$ zcat iris.csv.gz | csvstat # get summary statistics in bash of each variable in compressed csv file
    bash$ zcat iris.csv.gz | csvgrep -cSpecies -r "setosa" | gzip > iris_setosa.csv.gz # create new .csv.gz file with only data with Species == "setosa"
    bash$ gzip -d iris.csv.gz # this produces iris.csv again

**Comment by leeper** [comment]
Thanks, @trevorld! Important bug report here.

The key issue is, as @jsonbecker points out, that S3 dispatch is based on file extension (and we don't handle this file extension correctly) *and* besides we currently have no mechanism for even recognizing a two-part extension (like `.csv.gz`) in the `get_ext()` function. In the current design, this is seen as a .gz file and then not actually handled correctly. So, steps to ameliorate this are:

- [ ] Recognize two-part file extensions as a single extension. No idea how to do this correctly. Easiest fix is just treat this as an edge case and look explicitly for `.csv.gz`. That seems hack-ish, though.
- [ ] Write an `.export.rio_csv.gz()` method
- [ ] Write an `.import.rio_csv.gz()` method (which is basically just `.import.rio_csv.gz()` once the first issue is solved.
- [ ] Correctly implement export compression using `gzfile()` rather than (mistakenly) assuming this is supposed to be a tar archive and passing it through `tar()`.

We'll need to add tests for all of this.

**Comment by jsonbecker** [comment]
Since the two-part extension is most common with `*.gz` and `tools::file_ext` will say an extension is `*.gz`, I think the two-part problem can be solved largely with a separate path for `*.gz` files that checks for `tar` if `gz` and uses `untar` in those cases versus `gzfile` or similar in other cases.

**Comment by leeper** [comment]
Just pushed something that maybe solves this, but I need to test it more (later).

**Comment by trevorld** [comment]
Pull request #146 seems to get ``.csv.gz`` files working right in ``rio``.
