### ISSUE TITLE
Consider an option to use rtika to detect file type

### ISSUE THREAD

**Issue by jsonbecker** [leeper/rio#180]
It’d be cool to add an option that defaults to false that would use the new rtika package to detect file types rather than file extensions.

I’d be willing to take this work on if it seems interesting.

**Comment by jsonbecker** [comment]
I think that the CRAN version does not use rJava, instead it offers an install_* function and pushes system calls out to a CLI. So although you do need java on your system, you don’t need working rJava.

**Comment by bokov** [comment]
So, via magic numbers? Even those can fail. For example, .ODS and .XLSX files can have the same signatures. And they're both .zip files anyway, so that's another level of ambiguity.

On the other hand, it doesn't take that much time for `rio::import()` to try and fail at reading an incorrectly specified file, and doesn't introduce any new dependencies. So all it would take is a wrapper function on `rio::import()` that first tries the default parsing and if it fails, iterates over the entire list of supported file types calling `rio::import()` until it either succeeds or they all fail.

I have a proof of concept here (though I feel some discussion/brainstorming needed before submitting it as a PR)

**Comment by leeper** [comment]
I'm not super keen on trying to parse with every imaginable import function. That might produce some kind of unanticipated weird behavior if one of those underlying functions changes to start supporting different kind of file or if we add future functionality that changes the deterministic order of import attempts.

We could add a separate function that does that, though, like `try_import()`.

**Comment by leeper** [comment]
I think I'm not going to pursue this.
