### ISSUE TITLE
How to standardize return values and make package most useful?

### ISSUE THREAD

**Issue by leeper** [leeper/rio#22]
I've been thinking about our lingering questions about what packages to use in rio and what formats to support (#3, #12, #18, #19). What if we tried to setup the package to support returning any of the following standard data classes:

 - data.frame (base R; the default)
 - tbl_df (for dplyr)
 - data.table (for data.table)

This way users could open any file format and put it into whatever format they need instantly. This would allow us, for example, to use `fread` when someone requests a data.table but readr when someone requests a tbl_df, etc. This way rio serves as a gateway to the most important add-on packages without narrowly favoring any of them. It would also mean that we would have a type-consistent return value regardless of what particular file import function we use (so, we would have to wrap all of the `import.*` functions in commands that change the class of the return value.

Thoughts? @christophergandrud @hadley @chainsawriot @mattdowle @arunsrinivasan

**Comment by christophergandrud** [comment]
I think this sounds very reasonable. I guess the biggest issue is not
really what `import` is capable of wrapping, but what the default behaviour
is. (It might make the most sense to return data.frames and then have an
`returns` (or something) argument that could be `data.table` or `tbl_df`).

One thought: I'm not sure what the point of having separate `import.*`
wrappers would be. What would be more convenient about using separate
`import.*` functions compared to a user just calling `fread` or `read_csv`,
etc.?

**Comment by hadley** [comment]
A `tbl_df` _is_ a data frame, and behaves exactly the same way as a data frame unless you've explicitly loaded dplyr - that's why I've made it the default for readr, readxl etc.

**Comment by leeper** [comment]
@christophergandrud Sorry, that was unclear. I just meant that we currently call some other packages' functions directly but in a few cases we call non-exported functions (of the form `import.*`) in order to get them to behave the way we want. So I just meant that we might need to tweak some of those slightly to get the right return value.

**Comment by leeper** [comment]
@hadley I guess I was forgetting that. Then I guess that should probably be the default and a data.table will be the optional alternative.

**Comment by christophergandrud** [comment]
> "A `tbl_df` *is* a data frame, and behaves exactly the same way as a data
frame unless you've explicitly loaded dplyr"

One issue is that `tbl_df`'s have "odd" behaviour if you're not expecting a
data frame to be a `tbl_df` (e.g. some functions explicitly only work with
data.frames, as they look for `class(df) == 'data.frame'` rather than
`is.data.frame(df)`). While a really easy problem to solve, I'm wondering
if inexperienced users might find errors arising from these issues
baffling.

**Comment by hadley** [comment]
Do you have any specific function that do that? I'm assuming they aren't in base R.

**Comment by christophergandrud** [comment]
I remember running across this with user-created packages (though unfortunately I didn't note them at the time :(  ).

**Comment by arunsrinivasan** [comment]
@leeper thanks for the tag. Just caught up on the other links.

On `fread` being default - it makes the most sense to me for these reasons:

* It is quite mature.
* It's not only fast, but also simple to handle. 
* you can return a `data.frame` as well.

I understand that a) dealing with connections and b) dates are things that `read_csv()` provides. I'll up the priority and close the gap ASAP. I find routing to `read_*` on these two scenarios until then makes more sense and if that fails as well, then to base R.

Most people use `fread` (even if they don't use data.table), because they find `read.table`etc.. slow (one has to add quite a few additional arguments to get slight improvements). It makes less sense to me to use `read_csv()` for cases where I can read in faster. You can not design a package by assuming most people have only <100Mb file to read (or just one 100Mb file). 

Reading your description, it's clear that the intent is to make it extremely easy for the user, but it's not clear if it uses the most efficient implementations available for a given format.. (but your benchmarking of different packages and functions seem to suggest that speed is an important criteria as well).

One other note on `read_*`:

I'd find it strange if you allow to specify `data.frame` as my desired class in result, and it returns other additional stuff (same functionality aside). Additionally, if one runs my script / package in an environment with `dplyr` loaded, and has code like `DF[, col]` (which returns a vector), it'd return an error (since `dplyr` doesn't have `drop=FALSE` as well). It'd be nice if `read_*` also has an additional argument to just return `data.frame` (similar to how `data.table` does). Else, I'd suggest implementing that as an argument in your package and return just a `data.frame` if that's what is asked.

On `fwf`:

Your benchmark link shows some results to be `FALSE` on testing for `identical()`. Are you aware of that? Also, `LaF` seems to just open a connection, but not load anything yet. That could be the reason for it to be quite fast.. I guess you can load the entire file by doing: `DF = laf_open_fwf(..); DF = DF[1:nrow(DF), 1:ncol(DF)]`? Benchmarking by having identical results would be really helpful.

I'd suggest writing to authors of other (e.g.,: excel) packages to hear their views as well (with regard to those formats).

My 2 cents. HTH
Great job!
Arun.

**Comment by leeper** [comment]
I think the current result of this discussion is the following:

* `import` will always return an object of class "data.frame" (and only data.frame) by default
* An argument will be added to optionally return either a "tbl_df" or a "data.table"
* I'm willing to experiment with the idea of attaching a "tbl_df" class if dplyr is loaded, but not otherwise, but I'm concerned about the consistency of behavior
* Similarly, I could imagine doing the same for "data.table" if data.table is loaded
* We will not use LaF because it creates an otherwise unnecessary dependency

I am still considering the consequences of these principles for when/how to use `fread` and **readr** (i.e., whether the use of one versus the other should be dynamic and automatic, according to the above principles, or if it should be possible to call either of them as an explicit option).

**Comment by christophergandrud** [comment]
These seem perfectly reasonable to me.
