### ISSUE TITLE
Consider s3 classes for each data type to clean up import function

### ISSUE THREAD

**Issue by jsonbecker** [leeper/rio#42]
I was wondering if there would be interested in a PR that cleans up the `switch()` statement [on line 156](https://github.com/leeper/rio/blob/master/R/import.R#L156) so that it is a single function call. This could be accomplished by creating an s3 class for each data type. Because of the use of dot notation with the import functions, R would already dispatch properly to each function.

I am not sure if that pathway has speed implications, but I've personally enjoyed some of the flexibility of using classes when I developed a similar package.

**Comment by leeper** [comment]
I've been thinking about this and I think it's unnecessary overhead. It would make sense if the files had classes automatically, but we would have to manually define and then attach s3 classes to each file based on its extension then call a generic on the file. That's basically what's already happening without creating classes for each extension. I'm open to a pull request but it's not something I think I'm going to prioritize for my own coding efforts. Closing this for now.

**Comment by leeper** [comment]
I'm thinking this might actually be more feasible than before because it would allow other packages to write methods for importing new file types. Basically the process could work as follows:

1. `import("filename.extesion")` will create a one-element character vector will class `"importfile_extension"`
  - This will occur after all of the current handling of zips, remote files, etc.
2. An internal function `.import()` will be a new S3 generic.
3. `.import()` will dispatch to non-exported s3 methods for each file type (replacing the `switch()` in `import()`), each of which will return a data.frame
4. If there is no method, the default method `.import.default()` will just fail with an error.
5. `import()` will then perform `set_class()`, etc. as needed.
6. Do the same thing with `export()`, creating a hidden `.export()` generic.

Add-on packages can then create new `.import.importfile_filetype()` methods. This would enable for example a `sqliteio` package to be able to import/export from sqlite using the `import()` syntax:

```R
library("sqliteio")
import("db.sqlite")
```

This then solves the issue in #53, by creating extensibility for things that rio itself cannot support without a huge number of dependencies. (Some current functionality might best be moved there as well.) All of those packages can then be added as "Suggests" to rio.

**Comment by leeper** [comment]
The `io` apparently implements something akin to this (https://cran.r-project.org/web/packages/io/README.html). I think we can do it better if we try to follow a standardized file class system (such as discussed in: https://github.com/HenrikBengtsson/Wishlist-for-R/issues/9).

**Comment by jsonbecker** [comment]
I like it. Would it be helpful for me to try and stub this out over the weekend?

**Comment by leeper** [comment]
@jsonbecker want to make a feature branch? I suspect the implementation will involve some backtracking as we play around with it.

**Comment by jsonbecker** [comment]
@leeper sure thing-- best way to do that on my cloned version or do you want me to push directly to this repo in a new feature branch?

**Comment by leeper** [comment]
Maybe make a branch on your repo and then I'll pull it in.

**Comment by jsonbecker** [comment]
@leeper I'm working on export right now. I didn't fully understand how you were conceptualizing the file class system.

Were you imagining that `export` would have `exportfile_*` as classes? One thing I thought of as I was writing it that way to mirror the `importfile_*` is that we could instead have the classes be `rio_*`. I think that would be more in the spirit of the file class system idea as far as I can understand, and would allow for additional work with functions outside of `import` and `export` within rio that may want to do method dispatch.

I'll continue writing it up as `exportfile_*`, but that's an easy change I can make before submitting the PR.

**Comment by leeper** [comment]
@jsonbecker I like your intuition here. We don't want separate classes for import and export, but rather separate `.import()` and `.export()` methods for each filetype class (e.g., class `"rio_csv"` would get `.import.rio_csv()` and `.export.rio_csv()` methods).
