### ISSUE TITLE
Add filetypes: .raw, .asc, .dat, .mat (MATLAB)

### ISSUE THREAD

**Issue by Stan125** [leeper/rio#98]
Hi there, 

As I was trying out `rio` to maybe include it into [GREA](https://github.com/Stan125/GREA), I came across four filetypes which I occasionally use and which are not included. Including those filetypes might be a useful thing. You can look up the way I integrated them into my package [here](https://github.com/Stan125/GREA/blob/master/R/Read.R).

All the best,
Stani

**Comment by jsonbecker** [comment]
Looks like .mat uses `R.matlab::readMat`, but the other three extensions are just CSV files or a text file with some other separator? For `.raw`, `.dat`, and `.asc`, you can set `format = 'denim'` or `txt` or `csv`, whichever is appropriate.

For `readMat`, I'll defer to @leeper to see if he would want to import that function. If not, you could import/load `rio` and write your own function for it:

```
.import.rio_mat(function(file, ...) {
  readMat(con = file, ...)
}
```

And then just call `import(file = 'myfile.mat', format = 'mat')`.

This way `rio` can be imported into your package and have a custom method for that file type. You could theoretically provide methods the same as above for the other file types that alias to the appropriate existing `.import.rio_*` for that format.

**Comment by leeper** [comment]
I think @jsonbecker's answer here is the right way to handle these text files. I don't think `.raw`, `.dat`, or `.asc` are sufficiently standardized to merit handling them in a particular way, given that the `format` argument should provide sufficient flexibility here.

In terms of matlab support, there is [a feature branch on this repo](https://github.com/leeper/rio/tree/rmatio) with experimental support for this. I'd appreciate any feedback on it since I do not regularly work with Matlab files.
